title: "EK125"
author: "Stormy Attaway, Brian DePasquale, Christine Mulvey, Kenn Sebesta"
execute:
  execute_notebooks: force
launch_buttons:
  colab_url: "https://colab.research.google.com"
repository:
  url: "https://github.com/BU-EK125/EK125-notebooks"
  branch: main
